print("zadanie 1")
print(15*38)
print((3+4)*(5+9))
print(7//2)
print(48%5)
print((8+7+4+2)/4)
print(2**10)
print()
print(80*0.25)
print("zadanie 2")
print("a-55")
print("b-2")
print("d-(-1)")
print("e-256")
print("f-5")
print("g-0")
print("h-11")
print("i-True")
print("j-true")
print('False')
print("true")
print("False")
print(1)
print("Zadanie 17.")
wzrostcm=int(input('Ile masz wzrostu w centymetrach?: '))
print(f'Twoj wzrost w cm wynosi: {wzrostcm} centymetrow')
#1 stopa=30,48cm
nacale=round(wzrostcm/2.54,2)
stopy=nacale//12
reszta=nacale%12
print(f'Twoj wzrost wynosi {int(stopy)} stóp i {int(reszta)} cali')
print("zadanie 18.")
bok1=int(input('Wpisz dlugosc pierwszego boku: '))
bok2=int(input('Wpisz dlugosc drugiego boku: '))
bok3=int(input('Wpisz dlugosc trzeciego boku: '))
zmiennas=((bok1+bok2+bok3)/2)
heron=int((zmiennas*(zmiennas-bok1)*(zmiennas-bok2)*(zmiennas-bok3))**0.5)
print(f'Pole twojego trojkata wynosi: {heron}cm')
print('Podaj ponizsze dane by wyliczyc swoje BMI:')
masa=float(input('Ile wazysz?: '))
wzrost=float(input('Ile masz wzrostu w metrach?: '))
BMI=float(round(masa/wzrost**2, 2))
print(f'Twoje BMI wynosi: {BMI}')
print("zadanie 19")
import random
wynik1=random.randrange(1,7,1)
wynik2=random.randrange(1,7,1)
wynik3=random.randrange(1,7,1)
print(wynik1, wynik2, wynik3)
suma=wynik1+wynik2+wynik3
print(suma)